### ISSUE TITLE
Error when running other .world files

### ISSUE THREAD

**Issue by ltbd78** [tahsinkose/sjtu-drone#3]
When changed the launch file to run the search_and_rescue.world, I get this error:

```
[Wrn] [ModelDatabase.cc:340] Getting models from[http://gazebosim.org/models/]. This may take a few seconds.
[Err] [Node.cc:105] No namespace found
[Err] [Node.cc:105] No namespace found
[Err] [REST.cc:205] Error in REST request

libcurl: (51) SSL: no alternative certificate subject name matches target host name 'api.ignitionfuel.org'
```

For the garching_kitchen.world, the drone model falls through the floor.

**Comment by tahsinkose** [comment]
Hey @ltbd78,

That was due to the missing models that are not under that remote path. I had created those models for some another project locally and used it in here as well. My bad to not copy them over here :accept: 

See fix commit: https://github.com/tahsinkose/sjtu-drone/commit/9954ac8caa3e6972f61439028ed9300e2c3b541f

The drone falls through the floor, because its `z` is at 0. Please read README before reporting those as issues :slightly_smiling_face:
